export const ICON={
python: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
javascript: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
cpp: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg",
java: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
c: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg",
html: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
css: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
php: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg",
typescript: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
ruby: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-original.svg",
rust: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg",
swift: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg",
kotlin: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg",
perl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/perl/perl-original.svg",
go: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg",
csharp: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg",
bash: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg",
sql: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
mongodb: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
firebase: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg",
react: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
nodejs: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
}